### ISSUE TITLE
Failed when training DIOR-H dataset with other hbb algorithms

### ISSUE THREAD

**Issue by jazzyin** [liuyanyi/AD-Toolbox#1]
Many thanks to you for your great project, it is very useful for my current experiments. When I use faster  R-CNN to train the  DIOR-H dataset, I can get the training results normally.

However, when I try to use [Cascade R-CNN](https://github.com/open-mmlab/mmdetection/blob/master/configs/_base_/models/cascade_mask_rcnn_r50_fpn.py) or [RetinaNet](https://github.com/open-mmlab/mmdetection/blob/master/configs/_base_/models/retinanet_r50_fpn.py) to train the  DIOR-H dataset, displayed error. For example, when training with Cascade R-CNN, loss_cls and loss_bbox from Epoch [1][600/2839] will start to be displayed as NAN; when training with RetinaNet, the loss value will be randomly displayed as inf.

I am using two graphics cards and the batch size is 2, so I set lr=0.005 and nothing else has changed.

Looking forward to your help in answering this question.

**Comment by liuyanyi** [comment]
Thanks, but its weird faster rcnn works fine but other model got nan or inf.
I guess that may caused by data. You can check the annotations in dior dataset, maybe some negative nums appear or any other invalid bbox.
I'm working on my own stuff these days. I cant access to gpus so i cant debug that, if you have any progress, please comment here. Thank you very much.

**Comment by jazzyin** [comment]
When I revisited the Faser R-CNN log file, I found that there were NAN too, just because the number were fewer that didn't affect the results. I tried to use the official code of mmdetection, and the same problem occurs, so I am roughly sure that it should be the cause of the defect in the dataset itself. lol

Later, inspired by a respository, I set the self.min_size in datasets/xml_style.py to 0.5, and all the code can run normally after ignoring the bbox smaller than 0.5.

I had tried to modify it in AD-Toolbox without success. Due to time and code capability constraints, I now use mmdetection directly. 

Hope my experience can give you some inspiration.

**Comment by jazzyin** [comment]
By the way, if possible, could you test the DIOR-H dataset with Faster R-CNN (mmdetection version, backbone=ResNet 50, no other tricks)?
Because I found that the mAP in papers from Chinese papers to the top journal GRSL are different, sometimes the difference is a little big... Really confused....

**Comment by liuyanyi** [comment]
> By the way, if possible, could you test the DIOR-H dataset with Faster R-CNN (mmdetection version, backbone=ResNet 50, no other tricks)? Because I found that the mAP in papers from Chinese papers to the top journal GRSL are different, sometimes the difference is a little big... Really confused....

The model for hbb in this toolbox is exactly same with mmdetection, so only code in dataset is different. I update the configs and results, add min_size for dior, and there's no nan in faster rcnn and retinanet(still training, now 3 epoch).
I got 67.9 for AP50, and i found rcnn max per img in test cfg affect reslt.
With max_per_img=100, got 67.1, with 1000 got 67.4.

**Comment by jazzyin** [comment]
Got it, thank you very much！
